name: Deploy Website Main

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "blog/**"
      - "website/**"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'website skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build Website
        run: |
          cd website
          yarn install && yarn prettier
          if [ ! -n "$(git status --porcelain)" ]; then
            yarn build
            exit 0
          fi
          git config --global user.name 'GitHub Action'
          git config --global user.email 'github-action@users.noreply.github.com'
          git commit -am "[Prettier] Fix formatting"
          git push
          exit 1
          
      - name: Deploy Website 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: website/build
