name: "Sync personio jobs xml"
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch XML
        run: |
          curl https://wgtwo.jobs.personio.de/xml -o website/personio-jobs.xml
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          commit-message: "[autosync] Update personio job list"
          committer: github-actions <noreply@github.com>
          author: github-actions <noreply@github.com>
      - name: Enable Automerge on PR
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
      #--- start copy from website-deploy.yml
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Build Website
        run: |
          cd website
          yarn install && yarn prettier
          if [ ! -n "$(git status --porcelain)" ]; then
            yarn build
            exit 0
          fi
          exit 1

      - name: Deploy Website 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: website/build
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
      #--- end copy from website-deploy.yml
